package dev.lcdsmao.immersia

import android.view.KeyEvent

enum class KeyboardKey(
    val label: String,
    val keyCode: Int,
    val isModifier: Boolean = false,
) {
    ESC("Esc", KeyEvent.KEYCODE_ESCAPE),
    GRAVE("~", KeyEvent.KEYCODE_GRAVE),
    ONE("1", KeyEvent.KEYCODE_1),
    TWO("2", KeyEvent.KEYCODE_2),
    THREE("3", KeyEvent.KEYCODE_3),
    FOUR("4", KeyEvent.KEYCODE_4),
    FIVE("5", KeyEvent.KEYCODE_5),
    SIX("6", KeyEvent.KEYCODE_6),
    SEVEN("7", KeyEvent.KEYCODE_7),
    EIGHT("8", KeyEvent.KEYCODE_8),
    NINE("9", KeyEvent.KEYCODE_9),
    ZERO("0", KeyEvent.KEYCODE_0),
    MINUS("-", KeyEvent.KEYCODE_MINUS),
    EQUAL("=", KeyEvent.KEYCODE_EQUALS),
    BACKSPACE("Bksp", KeyEvent.KEYCODE_DEL),
    TAB("Tab", KeyEvent.KEYCODE_TAB),
    Q("Q", KeyEvent.KEYCODE_Q),
    W("W", KeyEvent.KEYCODE_W),
    E("E", KeyEvent.KEYCODE_E),
    R("R", KeyEvent.KEYCODE_R),
    T("T", KeyEvent.KEYCODE_T),
    Y("Y", KeyEvent.KEYCODE_Y),
    U("U", KeyEvent.KEYCODE_U),
    I("I", KeyEvent.KEYCODE_I),
    O("O", KeyEvent.KEYCODE_O),
    P("P", KeyEvent.KEYCODE_P),
    LEFT_BRACKET("[", KeyEvent.KEYCODE_LEFT_BRACKET),
    RIGHT_BRACKET("]", KeyEvent.KEYCODE_RIGHT_BRACKET),
    BACKSLASH("\\", KeyEvent.KEYCODE_BACKSLASH),
    CAPS("Caps", KeyEvent.KEYCODE_CAPS_LOCK),
    A("A", KeyEvent.KEYCODE_A),
    S("S", KeyEvent.KEYCODE_S),
    D("D", KeyEvent.KEYCODE_D),
    F("F", KeyEvent.KEYCODE_F),
    G("G", KeyEvent.KEYCODE_G),
    H("H", KeyEvent.KEYCODE_H),
    J("J", KeyEvent.KEYCODE_J),
    K("K", KeyEvent.KEYCODE_K),
    L("L", KeyEvent.KEYCODE_L),
    SEMICOLON(";", KeyEvent.KEYCODE_SEMICOLON),
    APOSTROPHE("'", KeyEvent.KEYCODE_APOSTROPHE),
    ENTER("Enter", KeyEvent.KEYCODE_ENTER),
    LEFT_SHIFT("Shift", KeyEvent.KEYCODE_SHIFT_LEFT, true),
    Z("Z", KeyEvent.KEYCODE_Z),
    X("X", KeyEvent.KEYCODE_X),
    C("C", KeyEvent.KEYCODE_C),
    V("V", KeyEvent.KEYCODE_V),
    B("B", KeyEvent.KEYCODE_B),
    N("N", KeyEvent.KEYCODE_N),
    M("M", KeyEvent.KEYCODE_M),
    COMMA(",", KeyEvent.KEYCODE_COMMA),
    PERIOD(".", KeyEvent.KEYCODE_PERIOD),
    SLASH("/", KeyEvent.KEYCODE_SLASH),
    RIGHT_SHIFT("Shift", KeyEvent.KEYCODE_SHIFT_RIGHT, true),
    LEFT_CTRL("Ctrl", KeyEvent.KEYCODE_CTRL_LEFT, true),
    LEFT_WIN("Win", KeyEvent.KEYCODE_META_LEFT, true),
    LEFT_ALT("Alt", KeyEvent.KEYCODE_ALT_LEFT, true),
    SPACE("Space", KeyEvent.KEYCODE_SPACE),
    RIGHT_ALT("Alt", KeyEvent.KEYCODE_ALT_RIGHT, true),
    RIGHT_CTRL("Ctrl", KeyEvent.KEYCODE_CTRL_RIGHT, true),
    LEFT("<", KeyEvent.KEYCODE_DPAD_LEFT),
    RIGHT(">", KeyEvent.KEYCODE_DPAD_RIGHT),
    UP("^", KeyEvent.KEYCODE_DPAD_UP),
    DOWN("v", KeyEvent.KEYCODE_DPAD_DOWN),
    PLACEHOLDER("", KeyEvent.KEYCODE_UNKNOWN);

    companion object {
        val leftHalf = listOf(
            listOf(ESC, ONE, TWO, THREE, FOUR, FIVE),
            listOf(TAB, Q, W, E, R, T),
            listOf(CAPS, A, S, D, F, G),
            listOf(LEFT_SHIFT, Z, X, C, V, B),
            listOf(LEFT_CTRL, LEFT_WIN, LEFT_ALT, PLACEHOLDER, GRAVE, SPACE),
        )

        val rightHalf = listOf(
            listOf(SIX, SEVEN, EIGHT, NINE, ZERO, MINUS, EQUAL),
            listOf(Y, U, I, O, P, LEFT_BRACKET, RIGHT_BRACKET),
            listOf(H, J, K, L, SEMICOLON, APOSTROPHE, BACKSLASH),
            listOf(N, M, COMMA, PERIOD, SLASH, UP, PLACEHOLDER),
            listOf(ENTER, BACKSPACE, PLACEHOLDER, PLACEHOLDER, LEFT, DOWN, RIGHT),
        )
    }
}
