package dev.lcdsmao.immersia

import androidx.compose.ui.text.Placeholder

enum class KeyboardKey(
    val label: String,
    val remoteName: String,
    val isModifier: Boolean = false,
) {
    ESC("Esc", "escape"),
    GRAVE("~", "grave"),
    ONE("1", "digit1"),
    TWO("2", "digit2"),
    THREE("3", "digit3"),
    FOUR("4", "digit4"),
    FIVE("5", "digit5"),
    SIX("6", "digit6"),
    SEVEN("7", "digit7"),
    EIGHT("8", "digit8"),
    NINE("9", "digit9"),
    ZERO("0", "digit0"),
    MINUS("-", "minus"),
    EQUAL("=", "equal"),
    BACKSPACE("Bksp", "backspace"),
    TAB("Tab", "tab"),
    Q("Q", "q"),
    W("W", "w"),
    E("E", "e"),
    R("R", "r"),
    T("T", "t"),
    Y("Y", "y"),
    U("U", "u"),
    I("I", "i"),
    O("O", "o"),
    P("P", "p"),
    LEFT_BRACKET("[", "oem_4"),
    RIGHT_BRACKET("]", "oem_6"),
    BACKSLASH("\\", "oem_5"),
    CAPS("Caps", "capslock"),
    A("A", "a"),
    S("S", "s"),
    D("D", "d"),
    F("F", "f"),
    G("G", "g"),
    H("H", "h"),
    J("J", "j"),
    K("K", "k"),
    L("L", "l"),
    SEMICOLON(";", "oem_1"),
    APOSTROPHE("'", "oem_7"),
    ENTER("Enter", "return"),
    LEFT_SHIFT("Shift", "leftshift", true),
    Z("Z", "z"),
    X("X", "x"),
    C("C", "c"),
    V("V", "v"),
    B("B", "b"),
    N("N", "n"),
    M("M", "m"),
    COMMA(",", "oem_comma"),
    PERIOD(".", "oem_period"),
    SLASH("/", "oem_2"),
    RIGHT_SHIFT("Shift", "rightshift", true),
    LEFT_CTRL("Ctrl", "leftctrl", true),
    LEFT_WIN("Win", "leftwindows", true),
    LEFT_ALT("Alt", "leftalt", true),
    SPACE("Space", "space"),
    RIGHT_ALT("Alt", "rightalt", true),
    RIGHT_CTRL("Ctrl", "rightctrl", true),
    LEFT("<", "left"),
    RIGHT(">", "right"),
    UP("^", "up"),
    DOWN("v", "down"),
    PLACEHOLDER("", "");

    companion object {
        val leftHalf = listOf(
            listOf(ESC, ONE, TWO, THREE, FOUR, FIVE),
            listOf(TAB, Q, W, E, R, T),
            listOf(CAPS, A, S, D, F, G),
            listOf(LEFT_SHIFT, Z, X, C, V, B),
            listOf(LEFT_CTRL, LEFT_WIN, LEFT_ALT, PLACEHOLDER, GRAVE, SPACE),
        )

        val rightHalf = listOf(
            listOf(SIX, SEVEN, EIGHT, NINE, ZERO, MINUS, EQUAL),
            listOf(Y, U, I, O, P, LEFT_BRACKET, RIGHT_BRACKET),
            listOf(H, J, K, L, SEMICOLON, APOSTROPHE, BACKSLASH),
            listOf(N, M, COMMA, PERIOD, SLASH, UP, PLACEHOLDER),
            listOf(ENTER, BACKSPACE, PLACEHOLDER, PLACEHOLDER, LEFT, DOWN, RIGHT),
        )
    }
}
